In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/Social_Network_Ads.csv")

In [ ]:
data.head()

    User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [ ]:
data["Gender"]=data["Gender"].astype("category")
data["Gender"]=data["Gender"].cat.codes

In [ ]:
data.head(2)

    User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510       1  19.0          19000.0          0
1  15810944       1  35.0          20000.0          0

In [ ]:
data=data.iloc[:,1:]
data.head()

   Gender   Age  EstimatedSalary  Purchased
0       1  19.0          19000.0          0
1       1  35.0          20000.0          0
2       0  26.0          43000.0          0
3       0  27.0          57000.0          0
4       1  19.0          76000.0          0

In [ ]:
data.isnull().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [ ]:
x.head(1)

   Gender   Age  EstimatedSalary
0       1  19.0          19000.0

In [ ]:
y.head(1)

0    0
Name: Purchased, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split